### ISSUE TITLE
Query does not work with MongoDB-3.2.0

### ISSUE THREAD

**Issue by kurtsergey** [share/sharedb-mongo#22] opened 2015-12-12 11:45 UTC
Mongo Error: unknown top level operator: $query

**Comment by vmakhaev** [comment] 2015-12-30 20:23
The issue is because $query operator is deprecated in Mongo 3.2
https://docs.mongodb.org/manual/reference/operator/meta/query/
Same as $orderby
https://docs.mongodb.org/manual/reference/operator/meta/orderby/

Prefered way now is to use cursor methods .sort(), etc

@nateps what is the strategy for sharedb-mongo here? Should we rewrite it to use cursor methods and convert user queries to cursor methods also? For ex: $orderby -> .sort()
I can make PR for this.

**Comment by vmakhaev** [comment] 2015-12-30 21:27
@nateps, just in case you will adopt the ideas PR is ready: https://github.com/share/sharedb-mongo/pull/23

**Comment by psirenny** [comment] 2016-02-29 22:31
@vmakhaev is this change backwards compatible with mongo 2.x?

**Comment by avital** [comment] 2016-04-29 16:20
@vmakhaev I don't think we can change sharedb-mongo to have cursor methods like on the new mongo driver, since ShareDB by designed has queries be represented as single POJOs. The sharedb-mongo README should have a description of the special keys in query objects and how they are treated.

@psirenny I tested the pull request against Mongo 2.6, 3.0 and 3.2 and they all pass the [improved test suite](https://github.com/share/sharedb-mongo/pull/31)

**Comment by avital** [comment] 2016-05-24 20:12
Should be fixed by #33. Thanks @vmakhaev for the work getting this fix going!

**Closed by avital** 2016-05-24 20:12 UTC
Labels: bug
